config/routes.rb
Rails.application.routes.draw do
  resources :court_types
  resources :values
  resources :schedulers
  resources :clients
  devise_for :admins
  resources :courts
  get "welcome/index"
  post "/", to: "welcome#index"
  root to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scheduler.rb
class Scheduler < ApplicationRecord
  include TranslateEnum
  belongs_to :client
  belongs_to :court
  #before_save :calculate_price
 
  enum status: { available: 0, unavailable: 1 }
  translate_enum :status
  validates_presence_of :start_time, :end_time
  validate :not_past_date, :court_available

  def court_available
    if Scheduler.where(court_id: court_id, date: date, start_time: start_time...end_time).count > 0
      errors.add(:time, " - Esse horário já está reservado, ou está com conflito com outro horário.")
    end
  end

  def not_past_date
    if date < Date.today
      errors.add(:date, "Não pode fazer reserva para datas passadas")
    end
  end

  def self.calculate_price(scheduler_params)
    # ERRO: estou procurando o Tipo_da_quadra pelo id do model Quadra, sempre virá errado
    # Preciso procurar o o Tipo_da_quadra por Court.court_type
    court_current = Court.find_by id: scheduler_params[:court_id]
    court_type_current = CourtType.find_by id: court_current.court_type_id
    if scheduler_params[:start_time].to_i < 18
      calculate_per_hour(scheduler_params[:end_time], scheduler_params[:start_time], court_type_current.day_price)
    else
      calculate_per_hour(scheduler_params[:end_time], scheduler_params[:start_time], court_type_current.night_price)
    end
  end 
  def self.calculate_per_hour(end_time, start_time, price)
    total_hours = (end_time.to_time - start_time.to_time)
    total = (total_hours / 3600) * price
  end

end

app/controllers/schedulers_controller.rb
class SchedulersController < ApplicationController
  before_action :set_scheduler, only: %i[ show edit update destroy ]
  before_action :get_clients, only: [:new, :edit]
  before_action :get_courts, only: [:new, :edit]
  # GET /schedulers or /schedulers.json
  def index
    @schedulers = Scheduler.all
  end

  # GET /schedulers/1 or /schedulers/1.json
  def show
  end

  # GET /schedulers/new
  def new
    court_id = params[:court_id]
    @court_id = court_id ? court_id : 5
    @scheduler = Scheduler.new
   
  end

  # GET /schedulers/1/edit
  def edit
  end

  # POST /schedulers or /schedulers.json
  def create
    @scheduler = Scheduler.new(scheduler_params)
    @scheduler.total = Scheduler.calculate_price(scheduler_params)

    respond_to do |format|
      if @scheduler.save
        format.html { redirect_to scheduler_url(@scheduler), notice: "Scheduler was successfully created." }
        format.json { render :show, status: :created, location: @scheduler }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedulers/1 or /schedulers/1.json
  def update
    respond_to do |format|
      if @scheduler.update(scheduler_params)
        format.html { redirect_to scheduler_url(@scheduler), notice: "Scheduler was successfully updated." }
        format.json { render :show, status: :ok, location: @scheduler }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedulers/1 or /schedulers/1.json
  def destroy
    @scheduler.destroy

    respond_to do |format|
      format.html { redirect_to schedulers_url, notice: "Scheduler was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_scheduler
    @scheduler = Scheduler.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def scheduler_params
    params.require(:scheduler).permit(:status, :date, :start_time, :end_time, :client_id, :court_id, :total)
  end

  def get_clients
    @clients = Client.all
  end

  def get_courts
    @courts = Court.all
  end
end

app/helpers/schedulers_helper.rb
module SchedulersHelper
end

app/views/schedulers/_form.html.erb
<%= form_with(model: scheduler, local: true) do |form| %>
  <% if scheduler.errors.any? %>
    <div id="error_explanation">
      <h4> <%= I18n.t("scheduler.errors.messages.not_saved", :count => scheduler.errors.count)%>

      <ul>
      <% scheduler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
 </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :court_id, style: "display: block" %>
    <%# name_court = Court.find(@court_id) %>
    <%#= name_court.name%>
    <%= form.collection_select :court_id, Court.all, :id, :name, {:prompt => "Selecione...", :selected => params[:court_id]}, {}%>
    <%#= form.text_field :court_id, value:"#{@court_id }", type:"hidden" %>

    <%#= form.collection_select :court_id, Court.all, :id, :name %>
    
  </div>
  <div class="form-group">
    <%= form.label :status, style: "display: block" %>
    <%#= form.select :status, options_for_select(Scheduler.translated_statuses {|translation, key, value| [key.titleize, Scheduler.statuses.key(value)]}, @scheduler.status) %>
    <%= form.select :status, options_for_select(Scheduler.statuses.map {|key, value| [key.titleize, Scheduler.statuses.key(value)]}, @scheduler.status) %>
    <%# f.select :status, options_for_select(f.object.class.translated_statuses.map { |translation, k, _v| [translation, k] })%> 
  </div>

  <div class="form-group">
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date, class:"form-control" %>
  </div>

  <div class="form-group">
   <%= form.label :start_time, style: "display: block" %>
     <%#= form.collection_select :hour_id, Hour.all, :id, :hour %>
     <%= form.time_field :start_time, 
      value: "%H:%M", 
      min: '07:00',
      max: '22:00', class:"form-control"%>
  </div>
  <div class="form-group">
   <%= form.label :end_time, style: "display: block" %>
     <%#= form.collection_select :hour_id, Hour.all, :id, :hour %>
     <%= form.time_field :end_time,
      value: "%H:%M", 
      min: '07:00',
      max: '22:00', class:"form-control"%>
  </div>
  

  <div class="form-group">
    <%= form.label :client_id, style: "display: block" %>
    <%= form.collection_select :client_id, Client.all, :id, :name %>
    <%#= form.text_field :client_id %>
    <%#= form.collection_select(:client_id, @clients, :id, :name, {}, {class:"form-control"}) %>
  
<br/><br/>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">
        <span class="icon text-white-50">
          <i class="fas fa-flag"></i>
          
        </span>
        <span class="text">Confirmar</span>
      </button>
     
  </div>
<% end %>

app/views/schedulers/_scheduler.html.erb
   <p>
    <strong>Quadra:</strong>
    <%= scheduler.court.name  %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= I18n.l(scheduler.date) %>
  </p>

  <p>
    <strong>Início:</strong>
    <%= scheduler.start_time.strftime("%H:%M") unless scheduler.start_time.nil? %>
  </p>
<p>
    <strong>Final:</strong>
    <%= scheduler.end_time.strftime("%H:%M") unless scheduler.end_time.nil? %>
  </p>
  <p>
    <strong>Cliente:</strong>
    <%= scheduler.client.name  %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= (scheduler.total) %>
  </p>

</div>

app/views/schedulers/edit.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= t('editing.scheduler')%></h1>

<%= render "form", scheduler: @scheduler %>

<br>

<div>
<%= link_to t('links.show'), @scheduler %> |
  <%= link_to t('links.back'), schedulers_path %>
  
</div>

app/views/schedulers/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Agendamentos</h1>
</div>
<hr>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
      <thead>
        <tr role="row">
          <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 57.0057px;">Quadra</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Data</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Início</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Final</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Valor</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Cliente</th>
     
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;"><%= link_to new_scheduler_path, class:"btn btn-success btn-circle btn-sm" do %>
              <i class="fa fa-plus"></i>
            <% end %></th>
        </thead>
        
          <tbody>
            <% @schedulers.each do |scheduler|%>
              <tr class="odd">
              <td class="sorting_1"><%=scheduler.court.name %></td>
                <td><%= I18n.l(scheduler.date) %></td>
               

                <td><%= scheduler.start_time.strftime("%H:%M") unless scheduler.start_time.nil? %></td>
                
                <td><%= scheduler.end_time.strftime("%H:%M") unless scheduler.end_time.nil? %></td>
                <td>R$ <%= scheduler.total%></td>
                <td><%= scheduler.client.name %></td>
                
                
                <td style="width: 10%">
                  <%= link_to edit_scheduler_path(scheduler), class:"btn btn-primary btn-circle btn-sm" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to scheduler_path(scheduler), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: scheduler.status.truncate(15))} do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      </div>
    </div>

app/views/schedulers/new.html.erb
<p style="color: green"><%= notice %></p>
<%= flash[:errors]%>
<h1><%= t('new.scheduler')%></h1>

<%= render "form", scheduler: @scheduler %>

<br>

<div>
  <%= link_to t('links.back'), schedulers_path %>
</div>

app/views/schedulers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @scheduler %>

<div>
  
  <%= link_to t('links.edit'), @scheduler %> |
  <%= link_to t('links.back'), schedulers_path %>

  <%= button_to "Apagar Agendamento", @scheduler, method: :delete %>
</div>