config/routes.rb
Rails.application.routes.draw do
  resources :court_types
  resources :values
  resources :schedulers
  resources :clients
  devise_for :admins
  resources :courts
  get "welcome/index"
  post "/", to: "welcome#index"
  root to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :schedulers
  enum status: { aluno: 0, visitante: 1, mensalista: 2 }
  validates_presence_of :name
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :status)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong><%= @client.class.human_attribute_name(:name) %></strong>
    <%= client.name %>
  </p>

  <p>
    <strong><%= @client.class.human_attribute_name(:phone) %></strong>
    <%= client.phone %>
  </p>

  <p>
    <strong><%= @client.class.human_attribute_name(:status) %></strong>
    <%= client.status %>
  </p>

</div>          

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %> 
    <div id="error_explanation">
    
      <h4> <%= I18n.t("client.errors.messages.not_saved", :count => client.errors.count)%>
    
    

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, options_for_select(Client.statuses.map {|key, value| [key.titleize, Client.statuses.key(value)]}, @client.status) %> 
    
  </div>
<br/><br/>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">
        <span class="icon text-white-50">
          <i class="fas fa-flag"></i>
        </span>
        <span class="text">Confirmar</span>
      </button>
     
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1><%= t('editing.client')%></h1>

<%= render 'form', client: @client %>

<%= link_to t('links.show'), @client %> |
<%= link_to t('links.back'), clients_path %>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Clientes</h1>
</div>
<hr>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
      <thead>
        <tr role="row">
          <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 57.0057px;">ID</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Clientes</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Telefone</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Tipo</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;"><%= link_to new_client_path, class:"btn btn-success btn-circle btn-sm" do %>
              <i class="fa fa-plus"></i>
            <% end %></th>
        </thead>
        
          <tbody>
            <% @clients.each do |client|%>
              <tr class="odd">
                <td class="sorting_1"><%= client.id %></td>
                <td><%= client.name %></td>
                <td><%= client.phone %></td>
                <td><%= client.status %></td>
                <td style="width: 10%">
                  <%= link_to edit_client_path(client), class:"btn btn-primary btn-circle btn-sm" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to client_path(client), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: client.name.truncate(15))} do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      </div>
    </div>

app/views/clients/new.html.erb
<h1><%= t('new.client')%></h1>

<%= render "form", client: @client %>

<br>

<div>
<%= link_to t('links.back'), clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to t('links.edit'), @client %> |
  <%= link_to t('links.back'), clients_path %> 

  <%= button_to "Apagar cliente", @client, method: :delete, class:"btn-danger" %>
</div>