config/routes.rb
Rails.application.routes.draw do
  resources :court_types
  resources :values
  resources :schedulers
  resources :clients
  devise_for :admins
  resources :courts
  get "welcome/index"
  post "/", to: "welcome#index"
  root to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/court.rb
class Court < ApplicationRecord
  belongs_to :court_type
  include TranslateEnum
  enum status: { available: 0, unavailable: 1 }
  translate_enum :status
end

app/models/court_type.rb
class CourtType < ApplicationRecord
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: %i[ show edit update destroy ]
  before_action :get_court_type, only: [:new, :edit]

  # GET /courts or /courts.json
  def index
    @courts = Court.all
  end

  # GET /courts/1 or /courts/1.json
  def show
  end

  # GET /courts/new
  def new
    @court = Court.new
  end

  # GET /courts/1/edit
  def edit
  end

  # POST /courts or /courts.json
  def create
    @court = Court.new(court_params)

    respond_to do |format|
      if @court.save
        format.html { redirect_to court_url(@court), notice: "Court was successfully created." }
        format.json { render :show, status: :created, location: @court }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courts/1 or /courts/1.json
  def update
    respond_to do |format|
      if @court.update(court_params)
        format.html { redirect_to court_url(@court), notice: "Court was successfully updated." }
        format.json { render :show, status: :ok, location: @court }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1 or /courts/1.json
  def destroy
    @court.destroy

    respond_to do |format|
      format.html { redirect_to courts_url, notice: "Court was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_court
    @court = Court.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def court_params
    params.require(:court).permit(:name, :status, :availability, :court_type_id)
  end

  def get_court_type
    @court_types = CourtType.all
  end
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/_form.html.erb
<%= form_with(model: court, local: true) do |form| %>
  <% if @court.errors.any? %>
    <div id="error_explanation">
      <h4> <%= I18n.t("court.errors.messages.not_saved", :count => court.errors.count)%>

      <ul>
      <% court.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :court_type %>
    <%= form.collection_select :court_type_id, CourtType.all, :id, :name, {:prompt => "Selecione...", :selected => [@court.court_type_id]}, {}%>
  </div>
  <div class="form-group">
   
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Court.statuses.map {|key, value| [key.titleize, Court.statuses.key(value)]}, @court.status) %>
  </div>
  

  <div class="form-group">
    <button type="submit" class="btn btn-primary">
        <span class="icon text-white-50">
          <i class="fas fa-flag"></i>
        </span>
        <span class="text">Confirmar</span>
      </button>
     
  </div>
<% end %>
<%= params.inspect %>

app/views/courts/edit.html.erb
<h1><%= t('editing.court')%></h1>

<%= render 'form', court: @court %>

<%= link_to t('links.show'), @court %> |
<%= link_to t('links.back'), courts_path %>

app/views/courts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"><%= (Court.model_name.human(count: @courts.count)).capitalize  %></h1>
</div>
<hr>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
      <thead>
        <tr role="row">
          <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 57.0057px;">ID</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Quadras</th>

          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;">Disponibilidade</th>
          <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 61.0057px;"><%= link_to new_court_path, class:"btn btn-success btn-circle btn-sm" do %>
              <i class="fa fa-plus"></i>
            <% end %></th>
        </thead>
        
          <tbody>
            <% @courts.each do |court|%>
              <tr class="odd">
                <td class="sorting_1"><%= court.id %></td>
                <td><%= court.name %></td>
                <td><%= court.class.human_attribute_name(court.status) %></td>
                <td style="width: 10%">
                  <%= link_to edit_court_path(court), class:"btn btn-primary btn-circle btn-sm" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to court_path(court), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: court.name.truncate(15))} do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      </div>
    </div>

app/views/courts/new.html.erb
<h1><%= t('new.court')%></h1>

<%= render 'form', court: @court %>

<%= link_to t('links.back'), courts_path %>

app/views/courts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @court.name %></h1>
<p>
  <strong><%= @court.class.human_attribute_name(:name) %>:</strong>
  <%= @court.name %>
</p>

<p>
  <strong><%= @court.class.human_attribute_name(:court_type) %>:</strong>
  <%= @court.court_type_id %>
</p>

<p>
  <strong><%= @court.class.human_attribute_name(:status) %>:</strong>
  <%= @court.status %>
</p>

<%= link_to t('links.edit'), edit_court_path(@court) %> |
<%= link_to t('links.back'), courts_path %>

<%= button_to "Apagar quadra", @court, method: :delete, class:"btn-primary" %>